fog_system = part_system_create()
fog_emitter = part_emitter_create(fog_system)
fog_type = part_type_create()
//spr_smoke(fog_type, spr_water_part,false,false,false)
part_emitter_region(fog_system, fog_emitter, x-32, x+32, y-32, y+32, ps_shape_rectangle, ps_distr_linear)
part_emitter_burst(fog_system, fog_emitter, fog_type, 5)
part_type_gravity(fog_type, .02, 270)
part_type_life(fog_type, room_speed*1.5, room_speed*3)
part_emitter_region(fog_system, fog_emitter, 0, room_width, 0, room_height, ps_shape_rectangle, ps_distr_invgaussian)
part_type_alpha3(fog_type, .025, .06, .25)part_type_color3(fog_type, c_ltgray, c_white, c_ltgray)part_type_orientation(fog_type, -15, 15, 0, 2, 0)
part_type_shape(fog_type, pt_shape_explosion)
part_type_scale(fog_type, 5, 5)
part_type_direction(fog_type, 180, 180, 0, 1)
part_type_speed(fog_type, .03, .03, 0, .05)